 version: '2'
 volumes:
  collected_static: {}
 services:

  # QED Django Channels front-end
  interface_server:
    restart: always
    build: .
    image: asgi-django:latest
    ports:
      - "8000:8000"
    volumes:
      - collected_static:/src/collected_static
      - .:/src  # map qed/ to container's /src for updating w/out rebuilding images
    # command: . config/set_env_vars.sh ${QED_CONFIG}  # negates running env var script before docker-compose up
    environment:
      - REDIS_HOSTNAME=redis
      - DOCKER_HOSTNAME=${HOSTNAME}
    # command: daphne -b 0.0.0.0 -p 8080 asgi_docker:channel_layer
    command: sh /src/entrypoint-interface.sh
    links:
      - redis

  # # Worker server that handles websocket channel
  worker_websocket:
    restart: always
    build: .
    image: asgi-django
    command: python manage.py runworker --exclude-channels=chemaxon.receive
    links:
      - redis
      # - qed_django
    environment:
      - REDIS_HOSTNAME=redis
      - DOCKER_HOSTNAME=${HOSTNAME}

  # # Worker server that handles ChemAxon channel
  worker_chemaxon:
    restart: always
    build: .
    image: asgi-django
    command: python manage.py runworker --only-channels=chemaxon.receive
    links:
      - redis
      # - qed_django
    environment:
      - REDIS_HOSTNAME=redis
      - DOCKER_HOSTNAME=${HOSTNAME}

  # Redis (message broker / channel layer)
  redis:
    image: redis:latest
    hostname: redis
    expose:
      - "6379"